#!/usr/bin/env zsh

### START-OF-ICON-MAP
function icon_map() {
     case "$1" in

     # from SF symbols app
     "Microsoft_Outlook")
          icon_result="􀍕"
          ;;
     "BoltAI")
          icon_result="􀋥"
          ;;
     "Cursor")
          icon_result="􀈎"
          ;;
     "WezTerm")
          icon_result="􀩼"
          ;;
     "Obsidian")
          icon_result="􀉞"
          ;;

     # from https://github.com/kvndrsslr/sketchybar-app-font
     "Live")
          icon_result=":ableton:"
          ;;
     "Adobe_Bridge"*)
          icon_result=":adobe_bridge:"
          ;;
     "Affinity_Designer")
          icon_result=":affinity_designer:"
          ;;
     "Affinity_Designer_2")
          icon_result=":affinity_designer_2:"
          ;;
     "Affinity_Photo")
          icon_result=":affinity_photo:"
          ;;
     "Affinity_Photo 2")
          icon_result=":affinity_photo_2:"
          ;;
     "Affinity_Publisher")
          icon_result=":affinity_publisher:"
          ;;
     "Affinity_Publisher 2")
          icon_result=":affinity_publisher_2:"
          ;;
     "Airmail")
          icon_result=":airmail:"
          ;;
     "Alacritty")
          icon_result=":alacritty:"
          ;;
     "Alfred")
          icon_result=":alfred:"
          ;;
     "Android_Messages")
          icon_result=":android_messages:"
          ;;
     "Android_Studio")
          icon_result=":android_studio:"
          ;;
     "Anytype")
          icon_result=":anytype:"
          ;;
     "App Eraser")
          icon_result=":app_eraser:"
          ;;
     "App_Store")
          icon_result=":app_store:"
          ;;
     "Arc")
          icon_result=":arc:"
          ;;
     "Atom")
          icon_result=":atom:"
          ;;
     "Audacity")
          icon_result=":audacity:"
          ;;
     "Bambu_Studio")
          icon_result=":bambu_studio:"
          ;;
     "MoneyMoney")
          icon_result=":bank:"
          ;;
     "Battle.net")
          icon_result=":battle_net:"
          ;;
     "Bear")
          icon_result=":bear:"
          ;;
     "BetterTouchTool")
          icon_result=":bettertouchtool:"
          ;;
     "Bilibili" | "哔哩哔哩")
          icon_result=":bilibili:"
          ;;
     "Bitwarden")
          icon_result=":bit_warden:"
          ;;
     "Blender")
          icon_result=":blender:"
          ;;
     "BluOS_Controller")
          icon_result=":bluos_controller:"
          ;;
     "Calibre")
          icon_result=":book:"
          ;;
     "Brave_Browser")
          icon_result=":brave_browser:"
          ;;
     "Calculator" | "Calculette")
          icon_result=":calculator:"
          ;;
     "Calendar" | "日历" | "Fantastical" | "Cron" | "Amie" | "Calendrier" | "Notion Calendar")
          icon_result=":calendar:"
          ;;
     "Caprine")
          icon_result=":caprine:"
          ;;
     "Citrix_Workspace" | "Citrix Viewer")
          icon_result=":citrix:"
          ;;
     "ClickUp")
          icon_result=":click_up:"
          ;;
     "Code" | "Code - Insiders")
          icon_result=":code:"
          ;;
     "Color Picker" | "数码测色计")
          icon_result=":color_picker:"
          ;;
     "CotEditor")
          icon_result=":coteditor:"
          ;;
     "Creative_Cloud")
          icon_result=":creative_cloud:"
          ;;
     "Cypress")
          icon_result=":cypress:"
          ;;
     "DataGrip")
          icon_result=":datagrip:"
          ;;
     "DataSpell")
          icon_result=":dataspell:"
          ;;
     "DaVinci_Resolve")
          icon_result=":davinciresolve:"
          ;;
     "Default")
          icon_result=":default:"
          ;;
     "CleanMyMac_X")
          icon_result=":desktop:"
          ;;
     "DEVONthink_3")
          icon_result=":devonthink3:"
          ;;
     "DingTalk" | "钉钉" | "阿里钉")
          icon_result=":dingtalk:"
          ;;
     "Discord" | "Discord Canary" | "Discord PTB")
          icon_result=":discord:"
          ;;
     "Docker" | "Docker Desktop")
          icon_result=":docker:"
          ;;
     "GrandTotal" | "Receipts")
          icon_result=":dollar:"
          ;;
     "Double_Commander")
          icon_result=":doublecmd:"
          ;;
     "Drafts")
          icon_result=":drafts:"
          ;;
     "Dropbox")
          icon_result=":dropbox:"
          ;;
     "Element")
          icon_result=":element:"
          ;;
     "Emacs")
          icon_result=":emacs:"
          ;;
     "Evernote_Legacy")
          icon_result=":evernote_legacy:"
          ;;
     "FaceTime" | "FaceTime 通话")
          icon_result=":face_time:"
          ;;
     "Figma")
          icon_result=":figma:"
          ;;
     "Final_Cut_Pro")
          icon_result=":final_cut_pro:"
          ;;
     "Finder" | "访达")
          icon_result=":finder:"
          ;;
     "Firefox")
          icon_result=":firefox:"
          ;;
     "Firefox Developer Edition" | "Firefox Nightly")
          icon_result=":firefox_developer_edition:"
          ;;
     "Folx")
          icon_result=":folx:"
          ;;
     "Fusion")
          icon_result=":fusion:"
          ;;
     "System_Preferences" | "System_Settings" | "系统设置" | "Réglages Système")
          icon_result=":gear:"
          ;;
     "GitHub_Desktop")
          icon_result=":git_hub:"
          ;;
     "Godot")
          icon_result=":godot:"
          ;;
     "GoLand")
          icon_result=":goland:"
          ;;
     "Chromium" | "Google_Chrome" | "Google_Chrome_Canary")
          icon_result=":google_chrome:"
          ;;
     "Grammarly_Editor")
          icon_result=":grammarly:"
          ;;
     "Home_Assistant")
          icon_result=":home_assistant:"
          ;;
     "Hyper")
          icon_result=":hyper:"
          ;;
     "IntelliJ_IDEA")
          icon_result=":idea:"
          ;;
     "Adobe_InDesign"* | "InDesign")
          icon_result=":indesign:"
          ;;
     "Inkdrop")
          icon_result=":inkdrop:"
          ;;
     "Inkscape")
          icon_result=":inkscape:"
          ;;
     "Insomnia")
          icon_result=":insomnia:"
          ;;
     "Iris")
          icon_result=":iris:"
          ;;
     "iTerm" | "iTerm2")
          icon_result=":iterm:"
          ;;
     "Jellyfin_Media_Player")
          icon_result=":jellyfin:"
          ;;
     "Joplin")
          icon_result=":joplin:"
          ;;
     "카카오톡" | "KakaoTalk")
          icon_result=":kakaotalk:"
          ;;
     "Kakoune")
          icon_result=":kakoune:"
          ;;
     "KeePassXC")
          icon_result=":kee_pass_x_c:"
          ;;
     "Keyboard_Maestro")
          icon_result=":keyboard_maestro:"
          ;;
     "Keynote" | "Keynote 讲演")
          icon_result=":keynote:"
          ;;
     "kitty")
          icon_result=":kitty:"
          ;;
     "League_of_Legends")
          icon_result=":league_of_legends:"
          ;;
     "LibreWolf")
          icon_result=":libre_wolf:"
          ;;
     "Adobe_Lightroom")
          icon_result=":lightroom:"
          ;;
     "Lightroom_Classic")
          icon_result=":lightroomclassic:"
          ;;
     "LINE")
          icon_result=":line:"
          ;;
     "Linear")
          icon_result=":linear:"
          ;;
     "LM_Studio")
          icon_result=":lm_studio:"
          ;;
     "LocalSend")
          icon_result=":localsend:"
          ;;
     "Logic_Pro")
          icon_result=":logicpro:"
          ;;
     "Logseq")
          icon_result=":logseq:"
          ;;
     "Canary_Mail" | "HEY" | "Mail" | "Mailspring" | "MailMate" | "Superhuman" | "Spark" | "邮件")
          icon_result=":mail:"
          ;;
     "MAMP" | "MAMP_PRO")
          icon_result=":mamp:"
          ;;
     "Maps" | "Google_Maps")
          icon_result=":maps:"
          ;;
     "Matlab")
          icon_result=":matlab:"
          ;;
     "Mattermost")
          icon_result=":mattermost:"
          ;;
     "Messages" | "信息" | "Nachrichten")
          icon_result=":messages:"
          ;;
     "Messenger")
          icon_result=":messenger:"
          ;;
     "Microsoft_Edge")
          icon_result=":microsoft_edge:"
          ;;
     "Microsoft_Excel")
          icon_result=":microsoft_excel:"
          ;;
     "Microsoft_Outlook")
          icon_result=":microsoft_outlook:"
          ;;
     "Microsoft_PowerPoint")
          icon_result=":microsoft_power_point:"
          ;;
     "Microsoft_Remote_Desktop")
          icon_result=":microsoft_remote_desktop:"
          ;;
     "Microsoft_Teams" | "Microsoft_Teams_(work_or_school)")
          icon_result=":microsoft_teams:"
          ;;
     "Microsoft_Word")
          icon_result=":microsoft_word:"
          ;;
     "Min")
          icon_result=":min_browser:"
          ;;
     "Miro")
          icon_result=":miro:"
          ;;
     "MongoDB_Compass"*)
          icon_result=":mongodb:"
          ;;
     "mpv")
          icon_result=":mpv:"
          ;;
     "Mullvad_Browser")
          icon_result=":mullvad_browser:"
          ;;
     "Music" | "音乐" | "Musique")
          icon_result=":music:"
          ;;
     "Neovide" | "neovide")
          icon_result=":neovide:"
          ;;
     "Neovim" | "neovim" | "nvim")
          icon_result=":neovim:"
          ;;
     "网易云音乐")
          icon_result=":netease_music:"
          ;;
     "Noodl" | "Noodl Editor")
          icon_result=":noodl:"
          ;;
     "NordVPN")
          icon_result=":nord_vpn:"
          ;;
     "Notability")
          icon_result=":notability:"
          ;;
     "Notes" | "备忘录")
          icon_result=":notes:"
          ;;
     "Notion")
          icon_result=":notion:"
          ;;
     "Nova")
          icon_result=":nova:"
          ;;
     "Numbers" | "Numbers 表格")
          icon_result=":numbers:"
          ;;
     "Obsidian")
          icon_result=":obsidian:"
          ;;
     "OBS")
          icon_result=":obsstudio:"
          ;;
     "OmniFocus")
          icon_result=":omni_focus:"
          ;;
     "1Password")
          icon_result=":one_password:"
          ;;
     "Open_Video_Downloader")
          icon_result=":open_video_downloader:"
          ;;
     "ChatGPT")
          icon_result=":openai:"
          ;;
     "OpenVPN_Connect")
          icon_result=":openvpn_connect:"
          ;;
     "Opera")
          icon_result=":opera:"
          ;;
     "OrcaSlicer")
          icon_result=":orcaslicer:"
          ;;
     "Orion" | "Orion_RC")
          icon_result=":orion:"
          ;;
     "Pages" | "Pages 文稿")
          icon_result=":pages:"
          ;;
     "Parallels_Desktop")
          icon_result=":parallels:"
          ;;
     "Parsec")
          icon_result=":parsec:"
          ;;
     "Preview" | "预览" | "Skim" | "zathura" | "Aperçu")
          icon_result=":pdf:"
          ;;
     "PDF_Expert")
          icon_result=":pdf_expert:"
          ;;
     "Adobe_Photoshop"*)
          icon_result=":photoshop:"
          ;;
     "PhpStorm")
          icon_result=":php_storm:"
          ;;
     "Pi-hole_Remote")
          icon_result=":pihole:"
          ;;
     "Pine")
          icon_result=":pine:"
          ;;
     "Podcasts" | "播客")
          icon_result=":podcasts:"
          ;;
     "PomoDone_App")
          icon_result=":pomodone:"
          ;;
     "Postman")
          icon_result=":postman:"
          ;;
     "Proton_Mail" | "Proton_Mail_Bridge")
          icon_result=":proton_mail:"
          ;;
     "PrusaSlicer" | "SuperSlicer")
          icon_result=":prusaslicer:"
          ;;
     "PyCharm")
          icon_result=":pycharm:"
          ;;
     "QQ")
          icon_result=":qq:"
          ;;
     "QQ音乐" | "QQMusic")
          icon_result=":qqmusic:"
          ;;
     "Quantumult_X")
          icon_result=":quantumult_x:"
          ;;
     "qutebrowser")
          icon_result=":qute_browser:"
          ;;
     "Raindrop.io")
          icon_result=":raindrop_io:"
          ;;
     "Reeder")
          icon_result=":reeder5:"
          ;;
     "Reminders" | "提醒事项" | "Rappels")
          icon_result=":reminders:"
          ;;
     "Replit")
          icon_result=":replit:"
          ;;
     "Rider" | "JetBrains_Rider")
          icon_result=":rider:"
          ;;
     "Safari" | "Safari浏览器" | "Safari_Technology_Preview")
          icon_result=":safari:"
          ;;
     "Sequel_Ace")
          icon_result=":sequel_ace:"
          ;;
     "Sequel_Pro")
          icon_result=":sequel_pro:"
          ;;
     "Setapp")
          icon_result=":setapp:"
          ;;
     "SF_Symbols")
          icon_result=":sf_symbols:"
          ;;
     "Signal")
          icon_result=":signal:"
          ;;
     "sioyek")
          icon_result=":sioyek:"
          ;;
     "Sketch")
          icon_result=":sketch:"
          ;;
     "Skype")
          icon_result=":skype:"
          ;;
     "Slack")
          icon_result=":slack:"
          ;;
     "Spark_Desktop")
          icon_result=":spark:"
          ;;
     "Spotify")
          icon_result=":spotify:"
          ;;
     "Spotlight")
          icon_result=":spotlight:"
          ;;
     "Sublime_Text")
          icon_result=":sublime_text:"
          ;;
     "Tana")
          icon_result=":tana:"
          ;;
     "TeamSpeak_3")
          icon_result=":team_speak:"
          ;;
     "Telegram")
          icon_result=":telegram:"
          ;;
     "Terminal" | "终端")
          icon_result=":terminal:"
          ;;
     "Typora")
          icon_result=":text:"
          ;;
     "Microsoft_To_Do" | "Things")
          icon_result=":things:"
          ;;
     "Thunderbird")
          icon_result=":thunderbird:"
          ;;
     "TickTick")
          icon_result=":tick_tick:"
          ;;
     "TIDAL")
          icon_result=":tidal:"
          ;;
     "Tiny_RDM")
          icon_result=":tinyrdm:"
          ;;
     "Todoist")
          icon_result=":todoist:"
          ;;
     "Toggl_Track")
          icon_result=":toggl_track:"
          ;;
     "Tor_Browser")
          icon_result=":tor_browser:"
          ;;
     "Tower")
          icon_result=":tower:"
          ;;
     "Transmit")
          icon_result=":transmit:"
          ;;
     "Trello")
          icon_result=":trello:"
          ;;
     "Tweetbot" | "Twitter")
          icon_result=":twitter:"
          ;;
     "MacVim" | "Vim" | "VimR")
          icon_result=":vim:"
          ;;
     "Vivaldi")
          icon_result=":vivaldi:"
          ;;
     "VLC")
          icon_result=":vlc:"
          ;;
     "VMware_Fusion")
          icon_result=":vmware_fusion:"
          ;;
     "VSCodium")
          icon_result=":vscodium:"
          ;;
     "Warp")
          icon_result=":warp:"
          ;;
     "WebStorm")
          icon_result=":web_storm:"
          ;;
     "微信" | "WeChat")
          icon_result=":wechat:"
          ;;
     "企业微信" | "WeCom")
          icon_result=":wecom:"
          ;;
     "WezTerm")
          icon_result=":wezterm:"
          ;;
     "WhatsApp" | "‎WhatsApp")
          icon_result=":whats_app:"
          ;;
     "Xcode")
          icon_result=":xcode:"
          ;;
     "Yandex Music")
          icon_result=":yandex_music:"
          ;;
     "Yuque" | "语雀")
          icon_result=":yuque:"
          ;;
     "Zed")
          icon_result=":zed:"
          ;;
     "Zeplin")
          icon_result=":zeplin:"
          ;;
     "zoom.us")
          icon_result=":zoom:"
          ;;
     "Zotero")
          icon_result=":zotero:"
          ;;
     "Zulip")
          icon_result=":zulip:"
          ;;
     *)
          icon_result=":default:"
          ;;
     esac
}
### END-OF-ICON-MAP

icon_map "$1"
echo "${icon_result}"
