#!/usr/bin/env zsh

# https://github.com/FelixKratz/dotfiles
# https://felixkratz.github.io/SketchyBar/config/bar

source "$CONFIG_DIR/env.sh" # Loads all defined colors

# bar props and defaults
source "$CONFIG_DIR/defaults.sh"

##### Left Side Items #####
source $ITEM_DIR/apple.sh
source $ITEM_DIR/aerospace_spaces.sh

##### Center Items (q, center, e) #####


##### Right Side Items #####
source $ITEM_DIR/aerospace_controls.sh

# source $ITEM_DIR/clock.sh
# source $ITEM_DIR/wifi.sh
# source $ITEM_DIR/battery.sh
# source $ITEM_DIR/volume.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/disk.sh
source $ITEM_DIR/outdated.sh

##### Finalizing Setup #####
sketchybar --update
sketchybar --hotload true
