#!/usr/bin/env bash

set -x

#
# VARIABLES
#
# seems macOS Sequoia uses 7 as gap
gap_top=20
gap_bottom=20
gap_left=20
gap_right=20
gap_inner=20
color_preselect=0xE02d74da

#
# GLOBAL SETTINGS
#
global_settings=(
    debug_output off
    external_bar off:40:0
    menubar_opacity 1.0
    mouse_follows_focus off
    focus_follows_mouse off
    display_arrangement_order default
    window_origin_display default
    window_placement second_child
    window_zoom_persist on
    window_shadow off
    window_opacity off
    window_opacity_duration 0.0
    active_window_opacity 1.00
    normal_window_opacity 1.00
    window_animation_duration 0.0
    window_animation_easing ease_out_circ
    insert_feedback_color ${color_preselect}
    split_ratio 0.50
    split_type auto
    mouse_modifier fn
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap
)
yabai -m config "${global_settings[@]}"

#
# SPACE SETTINGS (applied globally here)
# yabai -m config [--space <SPACE_SEL>] <space setting>
#
space_settings=(
    layout float
    top_padding ${gap_top}
    bottom_padding ${gap_bottom}
    left_padding ${gap_left}
    right_padding ${gap_right}
    window_gap ${gap_inner}
    auto_balance off
)
yabai -m config "${space_settings[@]}"

#
# WINDOW SETTINGS managed with skhd / sketchybar
#

#
# RULES
#

yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off

#
# SIGNALS
#

yabai -m signal --add event=window_created action="sketchybar --trigger yabai_window_created ID=\$YABAI_WINDOW_ID &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger yabai_window_destroyed ID=\$YABAI_WINDOW_ID &> /dev/null"
yabai -m signal --add event=window_moved action="sketchybar --trigger yabai_window_moved ID=\$YABAI_WINDOW_ID &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar --trigger yabai_window_focused ID=\$YABAI_WINDOW_ID &> /dev/null"
yabai -m signal --add event=window_minimized action="sketchybar --trigger yabai_window_minimized ID=\$YABAI_WINDOW_ID &> /dev/null"
yabai -m signal --add event=window_deminimized action="sketchybar --trigger yabai_window_deminimized ID=\$YABAI_WINDOW_ID &> /dev/null"

# event=application_launched, ID=\$YABAI_PROCESS_ID
# event=application_terminated, ID=\$YABAI_PROCESS_ID
# event=application_front_switched, $YABAI_PROCESS_ID, $YABAI_RECENT_PROCESS_ID
# event=application_activated, $YABAI_PROCESS_ID
# event=application_deactivated, $YABAI_PROCESS_ID
# event=application_visible, $YABAI_PROCESS_ID
# event=application_hidden, $YABAI_PROCESS_ID
# event=window_created, $YABAI_WINDOW_ID
# event=window_destroyed, $YABAI_WINDOW_ID
# event=window_focused, $YABAI_WINDOW_ID
# event=window_moved, $YABAI_WINDOW_ID
# event=window_resized, $YABAI_WINDOW_ID
# event=window_minimized, $YABAI_WINDOW_ID
# event=window_deminimized, $YABAI_WINDOW_ID
# event=window_title_changed, $YABAI_WINDOW_ID
# event=display_added, $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX
# event=display_removed, $YABAI_DISPLAY_ID
# event=display_moved, $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX
# event=display_resized, $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX
# event=display_changed, $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX, $YABAI_RECENT_DISPLAY_ID, $YABAI_RECENT_DISPLAY_INDEX

set +x
