#!/usr/bin/env bash

options=(
  style=round
  width=3.0
  hidpi=off
  active_color="gradient(top_left=0xff00ff00,bottom_right=0x00000000)"
  inactive_color=0x00000000
)

borders "${options[@]}"

blacklist="DeskMinder,com.appps.NewDesk"