#!/bin/bash

home_symbol=""
folder_symbol=" "

max_length=20
current_path=$(pwd)
home_directory=$(echo ~)

# Trim off the home directory if present
show_home_symbol=false
if [[ "$current_path" == "$home_directory"* ]]; then
    current_path=${current_path#"$home_directory"}
    show_home_symbol=true
fi

# awk code
trimmed_path=$(echo "$current_path" | awk -v max_len="$max_length" '
{
    prepend=".."
    append="..."
    trimmed = 0
    n = split($0, parts, "/")
    path = parts[n]

    if (length(path) > max_len) {
        trimmed = 1
        path = substr(path, 1, max_len - length(append)) append
    } else {
        for (i = n-1; i > 0; i--) {
            if (length(parts[i] "/" path) <= max_len) {
                path = parts[i] "/" path
            } else {
                trimmed = 1
                path = prepend path
                break
            }
        }
    }

    print path
    
}')

if $show_home_symbol; then
    echo "$home_symbol$trimmed_path"
else
    echo "$folder_symbol$trimmed_path"
fi
