#!/usr/bin/env bash

function get_js_env() {
  local dir="$1"
  if [[ -z "$dir" ]]; then
    dir="$PWD"
  fi

  while [[ "$dir" != "/" ]]; do
    if [[ -f "$dir/deno.json" ]]; then
      ICON=┓ 
      VERSION=$(deno --version | head -n1 | cut -d' ' -f2)
      return
    elif [[ -f "$dir/svelte.config.js" ]]; then
      ICON=""
      VERSION=$(svelte --version)
      return
    elif [[ -f "$dir/package.json" ]]; then
      if rg -q "react-dom" "$dir/package.json"; then
        ICON=""
        VERSION=$(node -p "require('$dir/package.json').dependencies['react-dom']")
        return
      else 
        # node
        if [[ -n "$(fd -d1 -e ts . "$dir" -1)" ]]; then
          ICON=""
        else
          ICON=""
        fi
        VERSION=$(node --version | cut -c 2-)
        return
      fi
    fi
    dir="$(dirname "$dir")"
  done
}


get_js_env "$1"

if [[ -n "$VERSION" ]]; then
  echo "$ICON $VERSION"
else
  echo "$ICON"
fi
