#!/bin/bash

local $shell = $1

if [[ $shell == "nu" ]]; then
    echo 󰫻󰬂 # NU
elif [[ $shell == "zsh" ]]; then
    echo  # apple
elif [[ $shell == "bash" ]]; then
    echo  # >
elif [[ $shell == "fish" ]]; then
    echo  # fish
else 
    echo  # apple
fi
